README.md
bin/dataproc_template_functions.sh
bin/start.sh
dependency-reduced-pom.xml
src/main/java/com/google/cloud/dataproc/templates/databases/README.md

Following are list of changes
README file - updated execution commands
start.sh - Modified the way base directory is identified. Fix for running with . start.sh
- Removed set -x and added echo command

Update README File and Shell script changes

---

.gitignore
bin/dataproc_template_constants.sh
bin/start.sh

added dynamic mvn download of grpc dependency and copying it to GCS JAR path.

remove hardcoded grpclb.jar path

---

README.md
bin/dataproc_template_constants.sh
bin/dataproc_template_functions.sh
bin/start.sh

Changes to shell scripts and ReadMe file for running templates against existing dataproc cluster.

Fr 20 dataproc

---

README.md
src/main/java/com/google/cloud/dataproc/templates/BaseTemplate.java
src/main/java/com/google/cloud/dataproc/templates/jdbc/JDBCToGCS.java
src/main/java/com/google/cloud/dataproc/templates/jdbc/README.md
src/main/java/com/google/cloud/dataproc/templates/main/DataProcTemplate.java
src/main/java/com/google/cloud/dataproc/templates/util/TemplateConstants.java
src/main/resources/template.properties

Jdbc to gcs

---

src/main/java/com/google/cloud/dataproc/templates/hive/HiveToBigQuery.java
src/main/java/com/google/cloud/dataproc/templates/hive/README.md
src/main/java/com/google/cloud/dataproc/templates/jdbc/JDBCToBigQuery.java
src/main/java/com/google/cloud/dataproc/templates/jdbc/README.md
src/main/java/com/google/cloud/dataproc/templates/util/TemplateConstants.java
src/main/resources/template.properties
src/test/java/com/google/cloud/dataproc/templates/hive/HiveToBigQueryTest.java

Code changes to have JDBC properties in sync for both JDBCTOGCS and JDBCTOBIGQUERY templates. 
- Removed Table , database names and added sql option
- Removed json file option for jdbc additional properties. JDBC url to be used for custom properties
- Updated README file

JDBCTOBIGQUERY template hardening

---

pom.xml
src/main/java/com/google/cloud/dataproc/templates/BaseTemplate.java
src/main/java/com/google/cloud/dataproc/templates/dataplex/DataplexGCStoBQ.java
src/main/java/com/google/cloud/dataproc/templates/dataplex/README.md
src/main/java/com/google/cloud/dataproc/templates/main/DataProcTemplate.java
src/main/java/com/google/cloud/dataproc/templates/util/DataplexUtil.java
src/main/java/com/google/cloud/dataproc/templates/util/DataprocTemplateException.java
src/main/java/com/google/cloud/dataproc/templates/util/TemplateConstants.java
src/main/resources/template.properties

This template will incrementally move data from a Dataplex GCS tables to BigQuery. 
It will identify new partitions in Dataplex GCS and copy them to BigQuery.

Dataplex gcs2bq

---

java/pom.xml
java/src/main/java/com/google/cloud/dataproc/templates/gcs/GCStoBigquery.java
java/src/main/java/com/google/cloud/dataproc/templates/hive/HiveToGCS.java
java/src/main/java/com/google/cloud/dataproc/templates/kafka/KafkaToBQ.java
java/src/main/java/com/google/cloud/dataproc/templates/main/DataProcTemplate.java
java/src/main/resources/template.properties
java/src/test/java/com/google/cloud/dataproc/templates/gcs/GCStoBigqueryTest.java
java/src/test/java/com/google/cloud/dataproc/templates/hive/HiveToGCSTest.java
java/src/test/java/com/google/cloud/dataproc/templates/kafka/KafkaToBQTest.java
java/src/test/java/com/google/cloud/dataproc/templates/main/DataProcTemplateTest.java

fixed failing test
updated a dependency

fixed test failures and dependency

---

README.md
python/README.md
python/dataproc_templates/hive/README.md

added blogpost link for hive to gcs

---

README.md
java/src/main/java/com/google/cloud/dataproc/templates/gcs/GCStoGCS.java

by applying mvn spotless:apply
@hhasija fyi

fix java build 

---

python/dataproc_templates/jdbc/jdbc_to_gcs.py

added header=true for csv writre
closes #258

JDBC to GCS fix

---

java/src/main/java/com/google/cloud/dataproc/templates/dataplex/DataplexGCStoBQ.java
java/src/main/java/com/google/cloud/dataproc/templates/dataplex/README.md
java/src/main/java/com/google/cloud/dataproc/templates/util/DataplexUtil.java
java/src/main/java/com/google/cloud/dataproc/templates/util/TemplateConstants.java

Adding support for Dataplex GCS tables without partitions

Dataplex GCS to BQ: support for GCS Dataplex tables without partitions

---

README.md
python/README.md
python/dataproc_templates/snowflake/README.md
python/dataproc_templates/snowflake/__init__.py
python/dataproc_templates/snowflake/snowflake_to_gcs.py
python/dataproc_templates/template_name.py
python/dataproc_templates/util/template_constants.py
python/main.py
python/test/snowflake/test_snowflake_to_gcs.py

Added Template Snowflake to GCS. Tested for all possible inputs i.e. json, parquet, avro, csv.

Adding template Snowflake to GCS

---

java/bin/start.sh
python/bin/dataproc_template_functions.sh
python/bin/start.sh

Add contact and feedback information fixes #251

Add contact and feedback information

---

python/notebooks/jdbc/README.md
python/notebooks/jdbc/mssql-to-postgres.ipynb

PR for Issue# 221
Notebook to migrate a database from Microsoft SQL Server to Posgtres. 
This notebook allows the following:
1. User to specify all the required parameters via widgets
2. Generates the complete list of tables from metadata. Alternatively, user can supply a list of tables
3. In case the row count for a table exceeds the threshold value, an integer primary key will be identified for that table and used for partitioning while reading and writing.
4. Creates the schemas for all tables in the list in target database
5. Runs JDBCToJDBC (Python template) for SQL Server to Postgresql data movement.
Tested with [AdventureWorks2019](https://github.com/Microsoft/sql-server-samples/releases/download/adventureworks/AdventureWorks2019.bak) database.

Sql to postgres Notebook

---

notebooks/mysql2spanner/MySqlToSpanner_notebook.ipynb

Reverts GoogleCloudPlatform/dataproc-templates#343

Revert "fix maven installation and job naming with lower case"

---

notebooks/oracle2bq/OracleToBigQuery_notebook.ipynb
notebooks/oracle2bq/README.md

Oracle2bq notebook

---

README.md
notebooks/README.md

added notebook links to main github page

---

README.md
notebooks/README.md
notebooks/oracle2spanner/OracleToSpanner_notebook.ipynb
notebooks/oracle2spanner/README.md

This notebook solution migrates data from oracle to spanner. Notebook uses JDBC to Spanner java template.
Closes #224

Oracle2spanner notebook solution

---

notebooks/mssql2postgresql/mssql-to-postgres-notebook.ipynb

Resolved Issue #341: Removed widgets and merged other fixes.

Mssql to postgres bug 341

---

python/main.py

Configure log4j to consider the log level for the spark classes

configure spark logs

---

README.md

#310  Please review. The blog has been published already to medium post.

added link to blog post for gsc to bigquery

---

README.md
notebooks/README.md

Added mssql2bq link to readme.md

---

java/src/main/resources/template.properties
java/src/test/java/com/google/cloud/dataproc/templates/databases/SpannerToGCSTest.java
java/src/test/java/com/google/cloud/dataproc/templates/gcs/GCSToSpannerTest.java
java/src/test/java/com/google/cloud/dataproc/templates/gcs/GCStoBigTableTest.java
java/src/test/java/com/google/cloud/dataproc/templates/gcs/GCStoBigqueryTest.java
java/src/test/java/com/google/cloud/dataproc/templates/gcs/GCStoGCSTest.java
java/src/test/java/com/google/cloud/dataproc/templates/gcs/GCStoJDBCTest.java
java/src/test/java/com/google/cloud/dataproc/templates/hive/HiveToGCSTest.java
java/src/test/java/com/google/cloud/dataproc/templates/jdbc/JDBCToGCSTest.java
java/src/test/java/com/google/cloud/dataproc/templates/kafka/KafkaToBQTest.java
java/src/test/java/com/google/cloud/dataproc/templates/s3/S3ToBigQueryTest.java

Will remove spark.sql.warehouse.dir property from template.properties as part of issue https://github.com/GoogleCloudPlatform/dataproc-templates/issues/487

Removed placeholder values in template.properties

---

java/src/main/java/com/google/cloud/dataproc/templates/gcs/GCSToJDBC.java
java/src/main/java/com/google/cloud/dataproc/templates/gcs/GCSToJDBCConfig.java
java/src/main/java/com/google/cloud/dataproc/templates/gcs/README.md
java/src/main/java/com/google/cloud/dataproc/templates/util/TemplateConstants.java

Added CSV to valid input formats and added relevant code to read section of template.

feat: Add csv as a valid input format for GCSTOJDBC Java template

---

python/bin/start.sh

fix: Updated start.sh for wrong attribute name

---

java/src/main/java/com/google/cloud/dataproc/templates/databases/CassandraToBqConfig.java
java/src/main/java/com/google/cloud/dataproc/templates/databases/CassandraToGCSConfig.java
java/src/main/java/com/google/cloud/dataproc/templates/gcs/GCSToJDBC.java
java/src/main/java/com/google/cloud/dataproc/templates/gcs/GCSToJDBCConfig.java
java/src/main/java/com/google/cloud/dataproc/templates/gcs/GCSToSpannerConfig.java
java/src/main/java/com/google/cloud/dataproc/templates/jdbc/JDBCToSpannerConfig.java
java/src/main/java/com/google/cloud/dataproc/templates/word/WordCount.java
java/src/main/resources/template.properties

1. Cassandra to BQ
2. Cassandra to GCS
3. GCS to JDBC
4. GCS to Spanner
5. JDBC to Spanner

fix: add default values to template.properties, remove duplicate save & unused prop in Wordcount

---

notebooks/oracle2bq/README.md

Fixed issue #483: Altered 3 links within the README document to reference files and directories with relative path instead of hard-coded github links

fix: issue #483. Corrected links in readme

---

notebooks/oracle2bq/README.md

Reverts GoogleCloudPlatform/dataproc-templates#571

chore: Revert "chore: merge changes from main to developement branch"

---

python/test/cassandra/test_cassandra_to_gcs.py

fix: fixed test cases

---

java/bin/start.sh

Missed this file in the previous PR

fix: add Spark runtime version to Java file

---

python/test/jdbc/test_jdbc_to_jdbc.py

Remove debug code from unit test

test: Remove debug code from unit test

---

java/bin/start.sh

tested with jenkins integration testing

fix: upgraded dataproc version to 1.1

---

java/src/main/java/com/google/cloud/dataproc/templates/bigquery/BigQueryToGCS.java
java/src/main/java/com/google/cloud/dataproc/templates/bigquery/README.md
java/src/main/java/com/google/cloud/dataproc/templates/gcs/GCStoBigquery.java
java/src/main/java/com/google/cloud/dataproc/templates/gcs/README.md
java/src/main/java/com/google/cloud/dataproc/templates/s3/README.md
java/src/main/java/com/google/cloud/dataproc/templates/s3/S3ToBigQuery.java
java/src/main/java/com/google/cloud/dataproc/templates/util/TemplateConstants.java
java/src/main/resources/template.properties

1. BQ to GCS
2. GCS to BQ
3. S3 to BQ

fix: 635 java write mode should be configurable via templateproperties

---

python/dataproc_templates/hive/hive_to_gcs.py

cc: @hhasija - Enabled partition level writes on GCS as a default behaviour, with exception of sql query being provided.

fix: Issue##485 - Enabled partition level writes in HIVE2GCS template

---

python/dataproc_templates/hive/hive_to_gcs.py

Fix for Issue#485 partition writes in HIVE2GCS template

fix: partition write fix in HIVE2GCS template

---

README.md
java/src/main/java/com/google/cloud/dataproc/templates/pubsub/README.md

This is a PR for adding the links for videos in the readme. #447

fix:447 Adding video links

---

README.md
notebooks/README.md

docs: Published article for MsSqltoBQ Notebook and added hyperlinks

---

python/dataproc_templates/hive/util/README.md
python/dataproc_templates/hive/util/hive_ddl_extractor.py
python/dataproc_templates/util/template_constants.py
python/test/hive/util/test_hive_ddl_extractor.py

feat: Added optional arguments to make DDL compatible with Spark Tables and BQ Translation API

Hive ddl extractor enhancement

---

python/.ci/Jenkinsfile

ci: added Jenkinsfile for python integration tests

---

java/pom.xml

fix: updated pom.xml to avoid commons-cli conflict in cluster mode

---

README.md
notebooks/README.md

docs: added Oracle to Postgres notebook blogpost link to README files

---

.github/workflows/commit-checker.yml

update commit-checker.yml to accept chore(deps) commit messages

fix: update commit-checker.yml

---

python/.ci/Jenkinsfile

Fixed integration test for MongoToBigQuery python template

fix: integration test for MongoToBigQuery python

---

README.md
java/.ci/Jenkinsfile
java/README.md
java/pom.xml
java/src/main/java/com/google/cloud/dataproc/templates/BaseTemplate.java
java/src/main/java/com/google/cloud/dataproc/templates/kafka/KafkaToBQDstream.java
java/src/main/java/com/google/cloud/dataproc/templates/kafka/README.md
java/src/main/java/com/google/cloud/dataproc/templates/main/DataProcTemplate.java
java/src/main/java/com/google/cloud/dataproc/templates/util/TemplateConstants.java
java/src/main/resources/template.properties
java/src/test/java/com/google/cloud/dataproc/templates/kafka/KafkaToBQDstreamTest.java

https://github.com/GoogleCloudPlatform/dataproc-templates/issues/897 
New java template  KafkaToBQDstream (Kafka To BQ via Dstream) for Dataproc

feat: java Kafka To BQ via Dstream template

---

python/dataproc_templates/bigquery/README.md
python/dataproc_templates/bigquery/bigquery_to_gcs.py
python/dataproc_templates/util/template_constants.py

feat: creating a pull request for #issue 828 to add partition column functionality for Bigquery to GCS template

feat: Issue 828 add partition column functionality from bq to gcs

---

java/src/main/java/com/google/cloud/dataproc/templates/jdbc/JDBCToBigQuery.java

fix: JDBCTOBQ removed duplicated code for read and write operations

---

python/.ci/Jenkinsfile
python/dataproc_templates/gcs/Dockerfile
python/dataproc_templates/gcs/README.md
python/dataproc_templates/hbase/Dockerfile
python/dataproc_templates/hbase/README.md
python/dataproc_templates/jdbc/README.md
python/dataproc_templates/jdbc/__init__.py
python/dataproc_templates/jdbc/jdbc_to_bigquery.py
python/dataproc_templates/jdbc/jdbc_to_gcs.py
python/dataproc_templates/jdbc/jdbc_to_jdbc.py
python/dataproc_templates/util/secret_manager.py
python/dataproc_templates/util/template_constants.py
python/requirements.txt
python/setup.py
python/test/jdbc/test_jdbc_to_bigquery.py
python/test/jdbc/test_jdbc_to_gcs.py
python/test/jdbc/test_jdbc_to_jdbc.py

fix:  Added secret capabilities for all python jdbc templates.

841 add support for secrets for jdbc connections

---

README.md

docs: adding blog for cassandra to bigquery

docs: adding blog for cassandra to bigquery

---

java/.ci/Jenkinsfile

updated integration tests to execute in parallel

fix: rebalanced integrations tests

---

.github/workflows/execute_jenkins_build_java.yml
.github/workflows/execute_jenkins_build_python.yml
.github/workflows/execute_jenkins_integration_tests_java.yml
.github/workflows/execute_jenkins_integration_tests_python.yml
.github/workflows/execute_jenkins_ui_integration_tests_java.yml

ci: run UI integration tests as part of every PR

---

java/.ci/Jenkinsfile
python/.ci/Jenkinsfile

commented hbase tests for python and Java

fix: commented hbase integ test for short time

---

python/dataproc_templates/elasticsearch/README.md
python/dataproc_templates/elasticsearch/elasticsearch_to_bq.py
python/dataproc_templates/util/template_constants.py
python/test/elasticsearch/test_elasticsearch_to_bq.py

Add Spark BigQuery connector options to Elasticsearch BigQuery Template

feat!: Add Spark BigQuery connector options

---

java/.ci/UiJenkinsfile
java/pom.xml

dataproc serverless runtime compatibility is 1.2 and dataproc server runtime compatibility is 2.2

feat!: java 17 and spark 3.5.1 upgrade
