pom.xml

Log4j version update because of CVE-2021-45105 vulnerability.
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-45105

Update log4j to 2.17 to address CVE-2021-45105

---

pom.xml
src/test/java/com/google/cloud/dataproc/templates/gcs/GCStoBigqueryTest.java
src/test/java/com/google/cloud/dataproc/templates/hive/HiveToBigQueryTest.java
src/test/java/com/google/cloud/dataproc/templates/hive/HiveToGCSTest.java
src/test/java/com/google/cloud/dataproc/templates/pubsub/PubSubToBQTest.java
src/test/java/com/google/cloud/dataproc/templates/s3/S3ToBigQueryTest.java

Specified slf4j dependencies to latest version to deal with CNFE errors on mvn install in unit tests.
This unmasked errors in tests related to the lack of a spark master url, so spark master was specified as local on the test's setup.

No class def found error

---

bin/start.sh

Fixing that we accidentally commented out the `mvn clean spotless:apply install -DskipTests` step.

Update start.sh to build the jar

---

.gitignore
README.md
java/README.md
java/pom.xml
java/src/main/java/com/google/cloud/dataproc/templates/BaseTemplate.java
java/src/main/java/com/google/cloud/dataproc/templates/main/DataProcTemplate.java
java/src/main/java/com/google/cloud/dataproc/templates/pubsub/PubSubToGCS.java
java/src/main/java/com/google/cloud/dataproc/templates/pubsub/README.md
java/src/main/java/com/google/cloud/dataproc/templates/util/TemplateConstants.java
java/src/main/resources/template.properties
java/src/test/java/com/google/cloud/dataproc/templates/pubsub/PubSubToGCSTest.java

Hi,
Please ignore the previous pull request https://github.com/GoogleCloudPlatform/dataproc-templates/pull/88
I have addressed all the previous review comments in this new pull request except the following:
- PubSubToGCS:runTemplate()  needs to have try-catch block because of the presence of JavaStreamingContext.awaitTerminationOrTimeout() method
-  If pubsub messages are coming in JSON format then the multuple pubsub records will be merged into a single file before writing to GCS. Same support needs to be added for Avro and I can  research it and do it in a later point.
Testing:
Successfully tested Avro and Json formats and output data was written to gs://pubsubtogcs_dev/output folder.

Pubsub to Gcs template review

---

java/src/main/java/com/google/cloud/dataproc/templates/dataplex/DataplexGCStoBQ.java
java/src/main/java/com/google/cloud/dataproc/templates/dataplex/README.md

Originally the template could migrate several tables in a single batch.
This PR simplifies the template by limiting it's functionality to a single table per run.
This is because handling table specific arguments while migrating several tables in a single batch was adding unnecessary complexity.

removing support for migration of several entities in a single run

---

java/src/main/java/com/google/cloud/dataproc/templates/dataplex/DataplexGCStoBQ.java
java/src/main/java/com/google/cloud/dataproc/templates/dataplex/README.md
java/src/main/java/com/google/cloud/dataproc/templates/util/DataplexUtil.java
java/src/main/java/com/google/cloud/dataproc/templates/util/DataprocTemplateException.java

Fixing the following bugs:
- The template was returning a successful exit code even if it failed 
- The template would fail when no new data was available in dataplex
- Dataplex INT64 fields where cast into Spark IntegerType instead of LongType
Adding the following Feature:
- User can now specify the target table name

Dataplex bugs fixes & new features 

---

README.md
python/README.md

This pull request adds the link to the blog post: Processing data from Hive to BigQuery using PySpark and Dataproc Serverless
Closes #129

Publishing HiveToBigquery Medium blogpost

---

java/README.md

[HiveToGCS Java Blogpost ](https://medium.com/@nehamodgil_21070/processing-and-migrating-large-data-tables-from-hive-to-gcs-using-java-and-dataproc-serverless-b6dbbae61c5d)

Update README with blogpost link for Hive to GCS Java template

---

python/README.md
python/dataproc_templates/util/__init__.py
python/dataproc_templates/util/argument_parsing.py
python/main.py
python/test/util/test_argument_parsing.py

This PR enables to user to provide Spark log levels as a parameter for the PySpark templates.
Default log level is set to INFO.
The parameter is optional, and it will be considered for all templates.
The documentation of it is in the python/README.md as it applies to all templates.
Closes #386

enable Spark level logging

---

notebooks/hive2bq/HiveToBigquery_notebook.ipynb

Due to recent changes in the google-auth-library-python-oauth module python was not able to connect to GCS and thus was not able to save audit data as csv in GCS.
Ref: https://github.com/googleapis/google-auth-library-python-oauthlib/pull/240/files#diff-63cdf7d9059947cf2f03b72a8137b8a1901de52f685705c251886d58a75b9381L8
Updates Google-auth library to required package to fix the issue.

Updated Google-auth python package

---

java/src/main/java/com/google/cloud/dataproc/templates/dataplex/DataplexGCStoBQ.java
java/src/main/java/com/google/cloud/dataproc/templates/dataplex/README.md
java/src/main/java/com/google/cloud/dataproc/templates/util/Dataplex/DataplexAPIUtil.java
java/src/main/java/com/google/cloud/dataproc/templates/util/Dataplex/DataplexAssetUtil.java
java/src/main/java/com/google/cloud/dataproc/templates/util/Dataplex/DataplexEntityUtil.java
java/src/main/java/com/google/cloud/dataproc/templates/util/DataplexUtil.java
java/src/main/java/com/google/cloud/dataproc/templates/util/TemplateConstants.java
java/src/main/resources/template.properties

This PR covers the following:
- Refactoring the Dataplex utils to avoid duplicate API calls
- Adding support for Dataplex targets. No users can specify Dataplex BQ Assets and Entities as targets

Dataplex target entity

---

notebooks/oracle2bq/OracleToBigQuery_notebook.ipynb
notebooks/oracle2spanner/OracleToSpanner_notebook.ipynb

These changes update the Oracle based notebooks to dynamically define the name of the instance client directory. Previously the name was hardcoded and had become out of date, this required the end user to fix.
Changed notebooks:
- oracle2bq/OracleToBigQuery_notebook.ipynb
- oracle2spanner/OracleToSpanner_notebook.ipynb
As part of these changes I also added `--no-verbose` options to `wget` commands. I only did this to the two notebooks I was changing for this issue. If these changes make it to main I'll raise another issue to do the same to other notebooks.
I've tested manually and also run this branch through integration-tests-python and build-job-python in Jenkins.

Issue 406: [Notebook] Oracle Instant Client Step Needs Updating

---

README.md
python/README.md

Issue #297: added blog for Pyspark GCS to JDBC template https://medium.com/google-cloud/import-data-from-gcs-to-jdbc-databases-using-dataproc-serverless-c7154b242430

Issue #297: added blog for Pyspark GCS to JDBC template

---

cloudbuild.yaml

cloud build config for building jar files for public GCS. closes #533

feat: added cloud build yaml

---

notebooks/generic_notebook/vertex_pipeline_pyspark.ipynb
notebooks/hive2bq/HiveToBigquery_notebook.ipynb
notebooks/mssql2bq/mssql-to-bigquery-notebook.ipynb
notebooks/mssql2postgresql/mssql-to-postgres-notebook.ipynb
notebooks/mysql2spanner/MySqlToSpanner_notebook.ipynb
notebooks/oracle2bq/OracleToBigQuery_notebook.ipynb
notebooks/oracle2spanner/OracleToSpanner_notebook.ipynb

[Issue Link](  https://github.com/GoogleCloudPlatform/dataproc-templates/issues/346
)
For this I have used os.getcwd() in places where I found the parameter 'WORKING_DIRECTORY'  hardcoded in each notebooks.  
Earlier path used in notebooks were  like this
` WORKING_DIRECTORY = "/home/jupyter/dataproc-templates/python/"`
What I did is used os.getcwd() to get current directory and naviagate to python folder using that.  This will work in case we are running it locally however when using PySpark hive cluster os.getcwd() will return '/' hence we need to manually set the directory path . Thus i have written this as a comment in notebook.
`cur_path = Path(os.getcwd())`
`WORKING_DIRECTORY = os.path.join(cur_path.parent.parent ,'python')`
`# If the above code doesn't fetches the correct path …

#Issue 346: Workaround for hardcoded working dir 

---

python/dataproc_templates/hive/util/README.md
python/dataproc_templates/hive/util/hive_ddl_extractor.py
python/dataproc_templates/util/template_constants.py
python/requirements.txt
python/test/hive/util/test_hive_ddl_extractor.py

Changes:
Added Optional Arguments:
a. HIVE_DDL_CONSIDER_SPARK_TABLES: Will remove "AS SERDE" from the SQL if set to TRUE
b. HIVE_DDL_TRANSLATION_DISPOSITION: Remove "LOCATION" parameter and "USING FORMAT" if set to TRUE
NOTE: using comes when it is a spark table and TRANSLATION API does not recognise it as a HIVE DDL
Example:
>>> spark.sql("show create table employees_partitioned").show(10,False)
|CREATE TABLE `default`.`employees_partitioned` (
`eid` INT,
`name` STRING,
`position` STRING,
`dept` STRING,
`part1` INT,
`part2` STRING)
USING text
PARTITIONED BY (part1, part2)
LOCATION 'hdfs://hive-cluster-m/user/hive/warehouse/partitiondb.db/employee'
TBLPROPERTIES (
'transient_lastDdlTime' = '1670464514',
'bucketing_version' = '2')
The above SQL gives error if supplied directly to the …

feat: Added optional arguments to make DDL compatible with Spark Tables and BQ Translation API

---

notebooks/generic_notebook/vertex_pipeline_pyspark.ipynb
notebooks/hive2bq/HiveToBigquery_notebook.ipynb
notebooks/mssql2bq/mssql-to-bigquery-notebook.ipynb
notebooks/mssql2postgresql/mssql-to-postgres-notebook.ipynb
notebooks/mysql2spanner/MySqlToSpanner_notebook.ipynb
notebooks/oracle2bq/OracleToBigQuery_notebook.ipynb
notebooks/oracle2spanner/OracleToSpanner_notebook.ipynb

This PR adds the runtime_config_version property = "1.1" to the DataprocPySparkBatchOp, when submitting dataproc serverless jobs from the notebooks, to fix the error caused by the new default runtime, incompatible with the dependencies that we are using, which were compiled against Scala 2.12.
fix #665

fix: add runtime_config_version to notebooks

---

java/src/main/java/com/google/cloud/dataproc/templates/jdbc/README.md

Updated jdbctospanner.output.batch.size property name in the docs

docs: fix JDBC To Spanner property name

---

notebooks/mysql2spanner/MySqlToSpanner_notebook.ipynb
notebooks/oracle2spanner/OracleToSpanner_notebook.ipynb

Removed references to GRPC jar file from two notebooks:
- OracleToSpanner_notebook.ipynb
- MySqlToSpanner_notebook.ipynb
I've tested the changes using `OracleToSpanner_notebook.ipynb` on branch `feature/issue-650-notebook-jdbc-refactor` and then ported to `main`. I was unable to test on `main` because the code is not SQLAlchemy 2.0 compatible. This will be resolved when merging `feature/issue-650-notebook-jdbc-refactor`.

fix: Exclude GRPC jar file from Spanner notebooks

---

python/README.md
python/bin/start.sh

feat: added support for running python templates in CLUSTER mode
